@startuml ERD_Cache

left to right direction
skinparam linetype ortho
skinparam ranksep 90
skinparam nodesep 70
hide circle
hide methods
hide stereotype

package "Module Caching Lớp đệm" {
  entity "SystemCache" as SystemCache {
    * key : String <<PK>>
    * type : String <<PK>>
    --
    * value : String
    * expiresAt : DateTime
    * createdAt : DateTime
    * updatedAt : DateTime
  }
}

@enduml
