@startuml Class_Cache

skinparam linetype ortho
skinparam classAttributeIconSize 0

package "Phan he Bo nho tam (Cache Module)" {

  class "Chuc Nang Bo Nho Tam\n(CacheController)" as CacheController {
    - service : CacheService
    + constructor()
    + set(req: Request, res: Response): Promise<Response>
    + get(req: Request, res: Response): Promise<Response>
    + delete(req: Request, res: Response): Promise<Response>
    + clearExpired(req: Request, res: Response): Promise<Response>
  }

  class "Dich Vu Bo Nho Tam\n(CacheService)" as CacheService {
    - repo : CacheRepository
    + constructor()
    + get(type: CacheType, key: String): Promise<any | null>
    + set(type: CacheType, key: String, value: any, ttlSeconds: Int): Promise<any>
    + delete(type: CacheType, key: String): Promise<any>
    + clearExpired(type: CacheType): Promise<any>
  }

  class "Luu Tru Bo Nho Tam\n(CacheRepository)" as CacheRepository {
    + get(type: CacheType, key: String): Promise<any | null>
    + set(type: CacheType, key: String, value: String, expiresAt: DateTime): Promise<any>
    + delete(type: CacheType, key: String): Promise<any>
    + clearExpired(type: CacheType): Promise<any>
  }
}

CacheController *-- CacheService
CacheService *-- CacheRepository

@enduml
